---
apiVersion: v1
kind: Namespace
metadata: 
    name: node-app-namespace
---
apiVersion: v1
kind: ServiceAccount
metadata: 
    name: node-deployer-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
    namespace: node-app-namespace
    name: node-deployer
rules:
- apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "apply"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
    name: deploy-node-app
    namespace: node-app-namespace
subjects:
- kind: ServiceAccount
    apiGroup: "" 
    name: node-deployer-account
    namespace: node-app-namespace
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: node-deployer