---
apiVersion: v1
kind: Service
metadata:
  namespace: node-app-namespace
  name: node-app-service
  label: 
    app: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: node-app-namespace
  name: node-app
  labels: 
    app: node-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: node-app
    template:
        metadata:
            labels:
                app: node-app
        spec:
            containers:
            - name: node-app-container
              image: sylviab/node_app:latest
              ports:
              - containerPort: 3000
                protocol: TCP
